export const DEFAULT_DAILY_CAPACITY = 300;
export const LIMITED_AVAILABILITY_THRESHOLD = 30;
export const RESCHEDULE_CUTOFF_DAYS = 2; // reschedule link expires N days before visit
export const CANCELLATION_CUTOFF_DAYS = 5; // cancellation blocked within N days of visit
export const RESCHEDULE_TOKEN_HOURS = 48; // token valid for this many hours before visit date
export const MAGIC_LINK_EXPIRY_MINUTES = 15;
export const DEFAULT_CLASS_DURATION_MINUTES = 60;
export const CLASS_GAP_MINUTES = 45;
export const MAX_CONCURRENT_CLASSES = 2;
export const MAX_CLASSES_PER_BOOKING = 2;
export const MAX_CLASSES_SMALL_GROUP = 1;
export const LARGE_GROUP_THRESHOLD = 60; // studentCount above this can book 2 classes
export const ACCOUNT_LOCKOUT_THRESHOLD = 5;
export const ACCOUNT_LOCKOUT_DURATION_MINUTES = 15;
export const MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024; // 5MB
export const ALLOWED_UPLOAD_TYPES = ["application/pdf", "image/jpeg", "image/png"] as const;
export const SCHOLARSHIP_BUDGET_DEFAULT = 50000;
export const BUS_REIMBURSEMENT_MAX_PER_BUS = 500;
export const DATA_RETENTION_YEARS_DEFAULT = 7;
