export enum BookingStatus {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  DECLINED = "DECLINED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  WAITLISTED = "WAITLISTED",
}

export enum GroupType {
  SCHOOL = "SCHOOL",
  HOMESCHOOL = "HOMESCHOOL",
  CORPORATE = "CORPORATE",
  ADHOC = "ADHOC",
  CONNECTIONS = "CONNECTIONS",
}

export enum PaymentMethod {
  PAID = "PAID",
  SCHOLARSHIP = "SCHOLARSHIP",
  INVOICE = "INVOICE",
}

export enum UserRole {
  ADMIN = "ADMIN",
  REGISTRAR = "REGISTRAR",
  CONNECTIONS_COORDINATOR = "CONNECTIONS_COORDINATOR",
  READ_ONLY = "READ_ONLY",
}

export enum ScholarshipStatus {
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  DENIED = "DENIED",
}

export enum BusReimbursementStatus {
  NOT_SUBMITTED = "NOT_SUBMITTED",
  SUBMITTED = "SUBMITTED",
  PROCESSED = "PROCESSED",
}

export enum EmailTriggerType {
  BOOKING_CONFIRMED_STANDARD = "BOOKING_CONFIRMED_STANDARD",
  BOOKING_PENDING_REVIEW = "BOOKING_PENDING_REVIEW",
  BOOKING_CONFIRMED_BY_REGISTRAR = "BOOKING_CONFIRMED_BY_REGISTRAR",
  BOOKING_DECLINED = "BOOKING_DECLINED",
  RESCHEDULE_COMPLETED = "RESCHEDULE_COMPLETED",
  RESCHEDULE_PENDING_REVIEW = "RESCHEDULE_PENDING_REVIEW",
  REMINDER_14_DAYS = "REMINDER_14_DAYS",
  POST_VISIT_SURVEY = "POST_VISIT_SURVEY",
  SCHOLARSHIP_APPROVED = "SCHOLARSHIP_APPROVED",
  SCHOLARSHIP_INCOMPLETE_10_DAYS = "SCHOLARSHIP_INCOMPLETE_10_DAYS",
  SCHOLARSHIP_INCOMPLETE_FOLLOWUP = "SCHOLARSHIP_INCOMPLETE_FOLLOWUP",
  BUS_REIMBURSEMENT_INFO = "BUS_REIMBURSEMENT_INFO",
}

export enum EmailStatus {
  SENT = "SENT",
  FAILED = "FAILED",
}

export enum AuditActorType {
  USER = "USER",
  SYSTEM = "SYSTEM",
}
