export const ErrorCode = {
  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  // Resources
  NOT_FOUND: "NOT_FOUND",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  CLASS_NOT_FOUND: "CLASS_NOT_FOUND",
  SEASON_NOT_FOUND: "SEASON_NOT_FOUND",
  // Conflicts / Business Rules
  CAPACITY_EXCEEDED: "CAPACITY_EXCEEDED",
  DATE_UNAVAILABLE: "DATE_UNAVAILABLE",
  DATE_BLACKOUT: "DATE_BLACKOUT",
  CLASS_CAPACITY_EXCEEDED: "CLASS_CAPACITY_EXCEEDED",
  CLASS_SLOT_UNAVAILABLE: "CLASS_SLOT_UNAVAILABLE",
  RESCHEDULE_TOKEN_INVALID: "RESCHEDULE_TOKEN_INVALID",
  RESCHEDULE_DISABLED: "RESCHEDULE_DISABLED",
  RESCHEDULE_WINDOW_CLOSED: "RESCHEDULE_WINDOW_CLOSED",
  CANCELLATION_WINDOW_CLOSED: "CANCELLATION_WINDOW_CLOSED",
  BOOKING_NOT_RESCHEDULABLE: "BOOKING_NOT_RESCHEDULABLE",
  DUPLICATE_SCHOLARSHIP: "DUPLICATE_SCHOLARSHIP",
  SEASON_NOT_PUBLISHED: "SEASON_NOT_PUBLISHED",
  REGISTRATION_CLOSED: "REGISTRATION_CLOSED",
  // ACME
  ACME_PUSH_FAILED: "ACME_PUSH_FAILED",
  // Server
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiErrorResponse {
  error: {
    code: ErrorCodeType;
    message: string;
    fields?: Record<string, string>;
  };
}
